export const URL_GIT = "https://github.com/julienmalard/constellation"
export const URL_RAPPORTS = "https://github.com/julienmalard/constellation/issues/new/choose"
export const URL_TÉLÉCHARGEMENTS = URL_GIT + "/releases"
export const IPA_TÉLÉCHARGEMENTS = "https://api.github.com/repos/julienmalard/constellation/releases"
export const RACINE_URL_DOCS = "https://constellation.readthedocs.org"
export const COURRIEL_CONTACT = "julien.malard@mail.mcgill.ca"
